/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Mayess (https://sketchfab.com/Mayess)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/arhan-r-881-3249fb2278cf427faab3d05c6aaa4f53
Title: ARHAN R-881
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={216.145}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Glass_����������������002_0'].geometry}
            material={materials['.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Glass_����������������003_0'].geometry}
            material={materials['.003']}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={216.145}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.camo1_Camo1_0.geometry}
            material={materials.Camo1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['camo1_����������������_0'].geometry}
            material={materials.material}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Camo2_����������������_0'].geometry}
          material={materials.material}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={216.145}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
